// Gerado a partir do baralho de Byron Knoll (CC0). Ver assets/cards/README.md.
import type { Card } from '../contracts/types';

export const cardImages: Record<string, number> = {
  '4_ouros': require('../../assets/cards/4_ouros.png'),
  '4_espadas': require('../../assets/cards/4_espadas.png'),
  '4_copas': require('../../assets/cards/4_copas.png'),
  '4_paus': require('../../assets/cards/4_paus.png'),
  '5_ouros': require('../../assets/cards/5_ouros.png'),
  '5_espadas': require('../../assets/cards/5_espadas.png'),
  '5_copas': require('../../assets/cards/5_copas.png'),
  '5_paus': require('../../assets/cards/5_paus.png'),
  '6_ouros': require('../../assets/cards/6_ouros.png'),
  '6_espadas': require('../../assets/cards/6_espadas.png'),
  '6_copas': require('../../assets/cards/6_copas.png'),
  '6_paus': require('../../assets/cards/6_paus.png'),
  '7_ouros': require('../../assets/cards/7_ouros.png'),
  '7_espadas': require('../../assets/cards/7_espadas.png'),
  '7_copas': require('../../assets/cards/7_copas.png'),
  '7_paus': require('../../assets/cards/7_paus.png'),
  'Q_ouros': require('../../assets/cards/Q_ouros.png'),
  'Q_espadas': require('../../assets/cards/Q_espadas.png'),
  'Q_copas': require('../../assets/cards/Q_copas.png'),
  'Q_paus': require('../../assets/cards/Q_paus.png'),
  'J_ouros': require('../../assets/cards/J_ouros.png'),
  'J_espadas': require('../../assets/cards/J_espadas.png'),
  'J_copas': require('../../assets/cards/J_copas.png'),
  'J_paus': require('../../assets/cards/J_paus.png'),
  'K_ouros': require('../../assets/cards/K_ouros.png'),
  'K_espadas': require('../../assets/cards/K_espadas.png'),
  'K_copas': require('../../assets/cards/K_copas.png'),
  'K_paus': require('../../assets/cards/K_paus.png'),
  'A_ouros': require('../../assets/cards/A_ouros.png'),
  'A_espadas': require('../../assets/cards/A_espadas.png'),
  'A_copas': require('../../assets/cards/A_copas.png'),
  'A_paus': require('../../assets/cards/A_paus.png'),
  '2_ouros': require('../../assets/cards/2_ouros.png'),
  '2_espadas': require('../../assets/cards/2_espadas.png'),
  '2_copas': require('../../assets/cards/2_copas.png'),
  '2_paus': require('../../assets/cards/2_paus.png'),
  '3_ouros': require('../../assets/cards/3_ouros.png'),
  '3_espadas': require('../../assets/cards/3_espadas.png'),
  '3_copas': require('../../assets/cards/3_copas.png'),
  '3_paus': require('../../assets/cards/3_paus.png'),
};

export const cardImage = (card: Card): number => cardImages[`${card.rank}_${card.suit}`];
